[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--enable-mutable-globals"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "Window",
  "Document",
  "Element",
  "HtmlElement",
  "WebSocket",
  "MessageEvent",
  "CloseEvent",
  "ErrorEvent",
  "BinaryType",
  "Blob",
  "FileReader",
  "Worker",
  "WorkerGlobalScope",
  "DedicatedWorkerGlobalScope",
  "BroadcastChannel",
  "MessageChannel",
  "MessagePort",
  "Storage",
  "Location",
  "Url",
  "Response",
  "Request",
  "Headers",
  "AbortController",
  "AbortSignal",
  "ReadableStream",
  "WritableStream",
  "TransformStream",
  "Crypto",
  "SubtleCrypto",
  "CryptoKey",
  "Navigator",
  "NetworkInformation",
] }
gloo = { version = "0.8", features = ["futures", "console", "storage", "net", "worker"] }
gloo-utils = "0.1"
wee_alloc = "0.4"
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.0", features = ["full"] }

[lib]
crate-type = ["cdylib", "rlib"]
