// SPDX-License-Identifier: MIT OR Apache-2.0
/// Cryptographic operations for EMRP: Ed25519 signatures (ring) and HPKE sealing (crate::sealing)
use crate::error::{CryptoError, Result};
use crate::synapse::blockchain::serialization::UuidWrapper;
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use pem::{EncodeConfig, LineEnding, Pem, encode_config, parse};
use ring::{
    rand::SystemRandom,
    signature::{self, Ed25519KeyPair, KeyPair},
};
use sha2::Digest;
use sha2::Sha256;

use std::collections::HashMap;
use uuid::Uuid;

/// Manages all cryptographic operations for EMRP using Ring
#[derive(Debug)]
pub struct CryptoManager {
    /// Our Ed25519 key pair for signing
    key_pair: Option<Ed25519KeyPair>,
    /// Known public keys of other entities (Ed25519 public keys, 32 bytes each)
    known_keys: HashMap<String, [u8; 32]>,
    /// Secure random number generator
    rng: SystemRandom,
    /// Our X25519 sealing key pair (P2 slice d), independent of the Ed25519 key
    sealing_key: Option<crate::sealing::SealingKeyPair>,
}

impl CryptoManager {
    /// Create a new crypto manager
    pub fn new() -> Self {
        Self {
            key_pair: None,
            known_keys: HashMap::new(),
            rng: SystemRandom::new(),
            sealing_key: None,
        }
    }

    /// Generate a new Ed25519 keypair for this entity
    pub fn generate_keypair(&mut self) -> Result<(String, String)> {
        // Generate Ed25519 key pair
        let pkcs8_bytes = Ed25519KeyPair::generate_pkcs8(&self.rng).map_err(|e| {
            CryptoError::KeyGeneration(format!("Ed25519 key generation failed: {}", e))
        })?;

        // Create the key pair from the generated bytes
        let key_pair = Ed25519KeyPair::from_pkcs8(pkcs8_bytes.as_ref())
            .map_err(|e| CryptoError::KeyGeneration(format!("Failed to create key pair: {}", e)))?;

        // Export private key in PKCS#8 format
        let private_pem = encode_config(
            &Pem::new("PRIVATE KEY".to_string(), pkcs8_bytes.as_ref().to_vec()),
            EncodeConfig::new().set_line_ending(LineEnding::LF),
        );

        // Export public key in DER format and convert to PEM
        let public_key_bytes = key_pair.public_key().as_ref();
        let public_pem = encode_config(
            &Pem::new("PUBLIC KEY".to_string(), public_key_bytes.to_vec()),
            EncodeConfig::new().set_line_ending(LineEnding::LF),
        );

        // Store the key pair
        self.key_pair = Some(key_pair);

        tracing::info!("Generated new Ed25519 keypair using Ring");
        Ok((private_pem, public_pem))
    }

    /// Load private key from PEM string
    pub fn load_private_key(&mut self, pem: &str) -> Result<()> {
        let pem_block = parse(pem).map_err(|e| CryptoError::InvalidKey(e.to_string()))?;

        // Parse the private key using Ring
        let key_pair = Ed25519KeyPair::from_pkcs8(pem_block.contents()).map_err(|e| {
            CryptoError::InvalidKey(format!("Failed to parse Ed25519 private key: {}", e))
        })?;

        self.key_pair = Some(key_pair);
        tracing::info!("Loaded Ed25519 private key from PEM using Ring");
        Ok(())
    }

    /// Import a public key for another entity
    pub fn import_public_key(&mut self, global_id: &str, pem: &str) -> Result<()> {
        let pem_block = parse(pem).map_err(|e| CryptoError::InvalidKey(e.to_string()))?;

        // Ed25519 public keys are exactly 32 bytes
        if pem_block.contents().len() != 32 {
            return Err(CryptoError::InvalidKey(
                "Ed25519 public key must be exactly 32 bytes".to_string(),
            ));
        }

        let mut public_key = [0u8; 32];
        public_key.copy_from_slice(pem_block.contents());

        self.known_keys.insert(global_id.to_string(), public_key);
        tracing::info!("Imported Ed25519 public key for {}", global_id);
        Ok(())
    }

    /// Get our public key in PEM format
    pub fn get_public_key_pem(&self) -> Result<String> {
        if let Some(key_pair) = &self.key_pair {
            let public_key_bytes = key_pair.public_key().as_ref();
            Ok(encode_config(
                &Pem::new("PUBLIC KEY".to_string(), public_key_bytes.to_vec()),
                EncodeConfig::new().set_line_ending(LineEnding::LF),
            ))
        } else {
            Err(CryptoError::KeyNotFound("No public key loaded".to_string()))
        }
    }

    /// Sign a message with our Ed25519 private key
    pub fn sign_message(&self, message: &str) -> Result<Vec<u8>> {
        let key_pair = self
            .key_pair
            .as_ref()
            .ok_or_else(|| CryptoError::KeyNotFound("No private key loaded".to_string()))?;

        // Ed25519 signs the message directly (no hashing needed)
        let signature = key_pair.sign(message.as_bytes());

        Ok(signature.as_ref().to_vec())
    }

    /// Verify a message signature using Ed25519
    pub fn verify_signature(
        &self,
        message: &str,
        signature: &[u8],
        sender_global_id: &str,
    ) -> Result<bool> {
        let sender_public_key = self.known_keys.get(sender_global_id).ok_or_else(|| {
            CryptoError::KeyNotFound(format!("No public key for {sender_global_id}"))
        })?;

        // Create an UnparsedPublicKey for verification
        let public_key = signature::UnparsedPublicKey::new(&signature::ED25519, sender_public_key);

        // Verify signature
        match public_key.verify(message.as_bytes(), signature) {
            Ok(()) => Ok(true),
            Err(_) => Ok(false),
        }
    }

    /// Our Ed25519 public key as raw bytes.
    pub fn public_key_bytes(&self) -> Result<[u8; 32]> {
        let key_pair = self
            .key_pair
            .as_ref()
            .ok_or_else(|| CryptoError::KeyNotFound("No private key loaded".to_string()))?;
        let mut out = [0u8; 32];
        out.copy_from_slice(key_pair.public_key().as_ref());
        Ok(out)
    }

    /// Sign `message` as its sender (sender-authentication spec §7). Truncates the timestamp to
    /// whole microseconds, sets the proof's `key_id`, and signs canonical input v1. Errors if no
    /// key pair is loaded, and never leaves an empty signature behind.
    pub fn sign_secure_message(&self, message: &mut crate::types::SecureMessage) -> Result<()> {
        use crate::sender_auth::{
            ProofAlg, SenderProof, canonical_input, key_id, truncate_timestamp_to_micros,
        };

        let key_pair = self
            .key_pair
            .as_ref()
            .ok_or_else(|| CryptoError::KeyNotFound("No private key loaded".to_string()))?;
        let public = self.public_key_bytes()?;
        truncate_timestamp_to_micros(message);
        message.sender_proof = SenderProof {
            alg: ProofAlg::Ed25519,
            key_id: key_id(&public),
            sig: Vec::new(),
        };
        let signature = key_pair.sign(&canonical_input(message));
        message.sender_proof.sig = signature.as_ref().to_vec();
        Ok(())
    }

    /// Generate a fresh X25519 sealing key pair and keep it. Returns (private PKCS#8 PEM, public
    /// SubjectPublicKeyInfo PEM). The key is independent of the Ed25519 signing key.
    pub fn generate_sealing_key(&mut self) -> Result<(String, String)> {
        let key = crate::sealing::SealingKeyPair::generate();
        let pems = (key.to_pkcs8_pem(), key.public_key().to_spki_pem());
        self.sealing_key = Some(key);
        Ok(pems)
    }

    /// Load our X25519 sealing key from a PKCS#8 PEM.
    pub fn load_sealing_key_pem(&mut self, pem: &str) -> Result<()> {
        self.sealing_key = Some(crate::sealing::SealingKeyPair::from_pkcs8_pem(pem)?);
        Ok(())
    }

    /// Our sealing key pair, if one is loaded.
    pub fn sealing_key(&self) -> Option<&crate::sealing::SealingKeyPair> {
        self.sealing_key.as_ref()
    }

    /// Our sealing public key as a SubjectPublicKeyInfo PEM.
    pub fn sealing_public_key_pem(&self) -> Result<String> {
        self.sealing_key
            .as_ref()
            .map(|key| key.public_key().to_spki_pem())
            .ok_or_else(|| CryptoError::KeyNotFound("No sealing key loaded".to_string()))
    }

    /// Seal `message`'s body to `recipient` (see `crate::sealing::seal`). Sign afterwards.
    pub fn seal_secure_message(
        &self,
        message: &mut crate::types::SecureMessage,
        recipient: &crate::sealing::SealingPublicKey,
    ) -> Result<()> {
        crate::sealing::seal(message, recipient)
    }

    /// Open `message`'s body with our sealing key (see `crate::sealing::open`).
    pub fn open_payload(&self, message: &crate::types::SecureMessage) -> crate::sealing::Payload {
        crate::sealing::open(message, self.sealing_key.as_ref())
    }

    /// Generate a secure hash of data
    pub fn hash_data(&self, data: &[u8]) -> String {
        let mut hasher = Sha256::default();
        hasher.update(data);
        let result = hasher.finalize();
        STANDARD.encode(result)
    }

    /// Generate a random message ID
    pub fn generate_message_id(&self) -> String {
        UuidWrapper::new(Uuid::new_v4()).to_string()
    }

    /// Check if we have a key for an entity
    pub fn has_key_for(&self, global_id: &str) -> bool {
        self.known_keys.contains_key(global_id)
    }

    /// Get list of entities we have keys for
    pub fn known_entities(&self) -> Vec<String> {
        self.known_keys.keys().cloned().collect()
    }
}

impl Default for CryptoManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keypair_generation() {
        let mut crypto = CryptoManager::new();
        let result = crypto.generate_keypair();
        assert!(result.is_ok());

        let (private_pem, public_pem) = result.unwrap();
        assert!(private_pem.starts_with("-----BEGIN PRIVATE KEY-----"));
        assert!(public_pem.starts_with("-----BEGIN PUBLIC KEY-----"));
    }

    #[test]
    fn test_message_signing() {
        let mut crypto1 = CryptoManager::new();
        let mut crypto2 = CryptoManager::new();

        let (_, pub1) = crypto1.generate_keypair().unwrap();
        let (_, _) = crypto2.generate_keypair().unwrap();

        crypto2.import_public_key("entity1", &pub1).unwrap();

        let message = "Important message";
        let signature = crypto1.sign_message(message).unwrap();
        let verified = crypto2
            .verify_signature(message, &signature, "entity1")
            .unwrap();

        assert!(verified);
    }
}
