// SPDX-License-Identifier: MIT OR Apache-2.0
/// Cryptographic operations for EMRP using Ring with Ed25519 signatures and AES-GCM encryption
use crate::error::{CryptoError, Result};
use crate::synapse::blockchain::serialization::UuidWrapper;
use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use pem::{EncodeConfig, LineEnding, Pem, encode_config, parse};
use ring::{
    rand::SystemRandom,
    signature::{self, Ed25519KeyPair, KeyPair},
};
use sha2::Digest;
use sha2::Sha256;

use std::collections::HashMap;
use uuid::Uuid;

/// Manages all cryptographic operations for EMRP using Ring
#[derive(Debug)]
pub struct CryptoManager {
    /// Our Ed25519 key pair for signing
    key_pair: Option<Ed25519KeyPair>,
    /// Known public keys of other entities (Ed25519 public keys, 32 bytes each)
    known_keys: HashMap<String, [u8; 32]>,
    /// Secure random number generator
    rng: SystemRandom,
}

impl CryptoManager {
    /// Create a new crypto manager
    pub fn new() -> Self {
        Self {
            key_pair: None,
            known_keys: HashMap::new(),
            rng: SystemRandom::new(),
        }
    }

    /// Generate a new Ed25519 keypair for this entity
    pub fn generate_keypair(&mut self) -> Result<(String, String)> {
        // Generate Ed25519 key pair
        let pkcs8_bytes = Ed25519KeyPair::generate_pkcs8(&self.rng).map_err(|e| {
            CryptoError::KeyGeneration(format!("Ed25519 key generation failed: {}", e))
        })?;

        // Create the key pair from the generated bytes
        let key_pair = Ed25519KeyPair::from_pkcs8(pkcs8_bytes.as_ref())
            .map_err(|e| CryptoError::KeyGeneration(format!("Failed to create key pair: {}", e)))?;

        // Export private key in PKCS#8 format
        let private_pem = encode_config(
            &Pem::new("PRIVATE KEY".to_string(), pkcs8_bytes.as_ref().to_vec()),
            EncodeConfig::new().set_line_ending(LineEnding::LF),
        );

        // Export public key in DER format and convert to PEM
        let public_key_bytes = key_pair.public_key().as_ref();
        let public_pem = encode_config(
            &Pem::new("PUBLIC KEY".to_string(), public_key_bytes.to_vec()),
            EncodeConfig::new().set_line_ending(LineEnding::LF),
        );

        // Store the key pair
        self.key_pair = Some(key_pair);

        tracing::info!("Generated new Ed25519 keypair using Ring");
        Ok((private_pem, public_pem))
    }

    /// Load private key from PEM string
    pub fn load_private_key(&mut self, pem: &str) -> Result<()> {
        let pem_block = parse(pem).map_err(|e| CryptoError::InvalidKey(e.to_string()))?;

        // Parse the private key using Ring
        let key_pair = Ed25519KeyPair::from_pkcs8(pem_block.contents()).map_err(|e| {
            CryptoError::InvalidKey(format!("Failed to parse Ed25519 private key: {}", e))
        })?;

        self.key_pair = Some(key_pair);
        tracing::info!("Loaded Ed25519 private key from PEM using Ring");
        Ok(())
    }

    /// Import a public key for another entity
    pub fn import_public_key(&mut self, global_id: &str, pem: &str) -> Result<()> {
        let pem_block = parse(pem).map_err(|e| CryptoError::InvalidKey(e.to_string()))?;

        // Ed25519 public keys are exactly 32 bytes
        if pem_block.contents().len() != 32 {
            return Err(CryptoError::InvalidKey(
                "Ed25519 public key must be exactly 32 bytes".to_string(),
            ));
        }

        let mut public_key = [0u8; 32];
        public_key.copy_from_slice(pem_block.contents());

        self.known_keys.insert(global_id.to_string(), public_key);
        tracing::info!("Imported Ed25519 public key for {}", global_id);
        Ok(())
    }

    /// Get our public key in PEM format
    pub fn get_public_key_pem(&self) -> Result<String> {
        if let Some(key_pair) = &self.key_pair {
            let public_key_bytes = key_pair.public_key().as_ref();
            Ok(encode_config(
                &Pem::new("PUBLIC KEY".to_string(), public_key_bytes.to_vec()),
                EncodeConfig::new().set_line_ending(LineEnding::LF),
            ))
        } else {
            Err(CryptoError::KeyNotFound("No public key loaded".to_string()))
        }
    }

    /// Encrypt a message for a specific recipient using AES-GCM
    /// Note: This uses a shared secret approach. In production, you'd derive a shared secret
    /// from ECDH or use a proper public key encryption scheme.
    pub fn encrypt_message(&self, message: &str, recipient_global_id: &str) -> Result<Vec<u8>> {
        // Verify we have the recipient's public key
        let _recipient_key = self.known_keys.get(recipient_global_id).ok_or_else(|| {
            CryptoError::KeyNotFound(format!("No public key for {recipient_global_id}"))
        })?;

        let message_bytes = message.as_bytes();
        self.encrypt_with_aes(message_bytes)
    }

    /// Encrypt message using AES-GCM
    fn encrypt_with_aes(&self, message: &[u8]) -> Result<Vec<u8>> {
        // Generate random AES key
        let mut aes_key_bytes = [0u8; 32];
        ring::rand::SecureRandom::fill(&self.rng, &mut aes_key_bytes)
            .map_err(|_| CryptoError::Encryption("Failed to generate AES key".to_string()))?;
        let aes_key = Key::<Aes256Gcm>::from_slice(&aes_key_bytes);

        // Generate random nonce
        let mut nonce_bytes = [0u8; 12];
        ring::rand::SecureRandom::fill(&self.rng, &mut nonce_bytes)
            .map_err(|_| CryptoError::Encryption("Failed to generate nonce".to_string()))?;
        let nonce = Nonce::from_slice(&nonce_bytes);

        // Encrypt message with AES
        let cipher = Aes256Gcm::new(aes_key);
        let encrypted_message = cipher
            .encrypt(nonce, message)
            .map_err(|e| CryptoError::Encryption(e.to_string()))?;

        // Store format: key(32) + nonce(12) + encrypted_message
        let mut result = Vec::new();
        result.extend_from_slice(&aes_key_bytes); // 32 bytes
        result.extend_from_slice(&nonce_bytes); // 12 bytes
        result.extend_from_slice(&encrypted_message);

        Ok(result)
    }

    /// Decrypt a message with our private key
    pub fn decrypt_message(&self, encrypted_data: &[u8]) -> Result<String> {
        if encrypted_data.len() < 32 + 12 {
            return Err(CryptoError::Decryption(
                "Invalid encrypted data format".to_string(),
            ));
        }

        // Extract components
        let aes_key_bytes = &encrypted_data[0..32];
        let nonce_bytes = &encrypted_data[32..44];
        let encrypted_message = &encrypted_data[44..];

        let aes_key = Key::<Aes256Gcm>::from_slice(aes_key_bytes);
        let nonce = Nonce::from_slice(nonce_bytes);
        let cipher = Aes256Gcm::new(aes_key);

        let decrypted_message = cipher
            .decrypt(nonce, encrypted_message)
            .map_err(|e| CryptoError::Decryption(e.to_string()))?;

        String::from_utf8(decrypted_message).map_err(|e| CryptoError::Decryption(e.to_string()))
    }

    /// Sign a message with our Ed25519 private key
    pub fn sign_message(&self, message: &str) -> Result<Vec<u8>> {
        let key_pair = self
            .key_pair
            .as_ref()
            .ok_or_else(|| CryptoError::KeyNotFound("No private key loaded".to_string()))?;

        // Ed25519 signs the message directly (no hashing needed)
        let signature = key_pair.sign(message.as_bytes());

        Ok(signature.as_ref().to_vec())
    }

    /// Verify a message signature using Ed25519
    pub fn verify_signature(
        &self,
        message: &str,
        signature: &[u8],
        sender_global_id: &str,
    ) -> Result<bool> {
        let sender_public_key = self.known_keys.get(sender_global_id).ok_or_else(|| {
            CryptoError::KeyNotFound(format!("No public key for {sender_global_id}"))
        })?;

        // Create an UnparsedPublicKey for verification
        let public_key = signature::UnparsedPublicKey::new(&signature::ED25519, sender_public_key);

        // Verify signature
        match public_key.verify(message.as_bytes(), signature) {
            Ok(()) => Ok(true),
            Err(_) => Ok(false),
        }
    }

    /// Generate a secure hash of data
    pub fn hash_data(&self, data: &[u8]) -> String {
        let mut hasher = Sha256::default();
        hasher.update(data);
        let result = hasher.finalize();
        STANDARD.encode(result)
    }

    /// Generate a random message ID
    pub fn generate_message_id(&self) -> String {
        UuidWrapper::new(Uuid::new_v4()).to_string()
    }

    /// Check if we have a key for an entity
    pub fn has_key_for(&self, global_id: &str) -> bool {
        self.known_keys.contains_key(global_id)
    }

    /// Get list of entities we have keys for
    pub fn known_entities(&self) -> Vec<String> {
        self.known_keys.keys().cloned().collect()
    }
}

impl Default for CryptoManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keypair_generation() {
        let mut crypto = CryptoManager::new();
        let result = crypto.generate_keypair();
        assert!(result.is_ok());

        let (private_pem, public_pem) = result.unwrap();
        assert!(private_pem.starts_with("-----BEGIN PRIVATE KEY-----"));
        assert!(public_pem.starts_with("-----BEGIN PUBLIC KEY-----"));
    }

    #[test]
    fn test_message_encryption() {
        let mut crypto1 = CryptoManager::new();
        let mut crypto2 = CryptoManager::new();

        let (_, pub1) = crypto1.generate_keypair().unwrap();
        let (_, pub2) = crypto2.generate_keypair().unwrap();

        crypto1.import_public_key("entity2", &pub2).unwrap();
        crypto2.import_public_key("entity1", &pub1).unwrap();

        let message = "Hello, World!";
        let encrypted = crypto1.encrypt_message(message, "entity2").unwrap();
        let decrypted = crypto2.decrypt_message(&encrypted).unwrap();

        assert_eq!(message, decrypted);
    }

    #[test]
    fn test_message_signing() {
        let mut crypto1 = CryptoManager::new();
        let mut crypto2 = CryptoManager::new();

        let (_, pub1) = crypto1.generate_keypair().unwrap();
        let (_, _) = crypto2.generate_keypair().unwrap();

        crypto2.import_public_key("entity1", &pub1).unwrap();

        let message = "Important message";
        let signature = crypto1.sign_message(message).unwrap();
        let verified = crypto2
            .verify_signature(message, &signature, "entity1")
            .unwrap();

        assert!(verified);
    }

    #[test]
    fn test_large_message_encryption() {
        let mut crypto1 = CryptoManager::new();
        let mut crypto2 = CryptoManager::new();

        let (_, pub1) = crypto1.generate_keypair().unwrap();
        let (_, pub2) = crypto2.generate_keypair().unwrap();

        crypto1.import_public_key("entity2", &pub2).unwrap();
        crypto2.import_public_key("entity1", &pub1).unwrap();

        let message = "A".repeat(1000); // Large message
        let encrypted = crypto1.encrypt_message(&message, "entity2").unwrap();
        let decrypted = crypto2.decrypt_message(&encrypted).unwrap();

        assert_eq!(message, decrypted);
    }
}
